### ISSUE TITLE
Cannot download uhgv-toolkit

### ISSUE THREAD

**Issue by haleyhallowell** [snayfach/UHGV#59]
Hi Stephen, 

I'm super excited to start using the updated database, as i have been utilizing MGV for a while now. I am trying to install the UHGV-toolkit through the tutorial to classify viral sequences. However, when i run: 

`pip install git+https://github.com/snayfach/UHGV-toolkit.git --user`

It is prompting me for my username and password. I input my username (haleyhallowell) and a personal access token, but i am not able to download it. 

Is UHGV-toolkit for beta-users only currently? Or is access currently restricted? Thanks for your help and development on these invaluable databases/tools!

**Comment by meenachakra** [comment]
I'm having the same issue!

**Comment by meenachakra** [comment]
I was having this same issue, but now it's not even prompting me for my username and password - just gets stuck after the following error message --
![Screenshot 2023-07-10 at 2 31 34 PM](https://github.com/snayfach/UHGV/assets/75635229/ed46a1e4-b006-4b8c-957c-4f9351396970)

**Comment by snayfach** [comment]
Thanks for the issue! I'll look into this shortly

**Comment by meenachakra** [comment]
Thanks!!

**Comment by snayfach** [comment]
This should be fixed now

**Comment by meenachakra** [comment]
Thanks! Hmm, I'm getting the same issue/error, with or without the user flag. Does the UHGV-toolkit repository exist? I don't see it under your repos.

**Comment by meenachakra** [comment]
As an additional detail, it's not an issue with connecting to Github from my terminal since I'm able to push changes to my repos using my username and personal access token.

**Comment by snayfach** [comment]
Hi Meena, I should have specified that I updated the readme. The command is now `pip install git+https://github.com/snayfach/UHGV.git`

**Comment by meenachakra** [comment]
Oh, great, thank you so much!
