### ISSUE TITLE
Not writing output files but still says 'Success!' 

### ISSUE THREAD

**Issue by haleyhallowell** [snayfach/UHGV#60]
Hi Stephen, 

So sorry for the back to back issue requests. After your fix i was able to download the toolkit (and dependencies) and database easily (thanks!!). I ran the uhgv-toolkit in the following way: 

`uhgv-tools classify -i ../mappings/final_vOTUs_dedup.fna -o uhgv -d /home/hhallow1/scratch4-jsuez1/shared_databases/UHGV/uhgv-db-v0.4/ -t 10`

Looking at the `uhgv` output directory, i am only seeing a directory called `tmp`. Looking further into the log file, this is what i am seeing: 

> UHGV-tools v0.0.1: classify
>
> [1/10] Reading input sequences
> [2/10] Reading database sequences
> [3/10] Calculating nucleotide similarity with blastn
> [4/10] Identifying genes using prodigal-gv
> [5/10] Performing self alignment
> [6/10] Aligning proteins to database
> [7/10] Calculating amino acid similarity scores
> 
> Success!
> Elapsed time (s): 564.79
> Peak RAM usage (GB): 7.6

For reference, this is what the database directory look like: 

`genomes.fna  genomes.nhr  genomes.not  genomes.nto          proteins.faa
genomes.log  genomes.nin  genomes.nsq  genome_taxonomy.tsv  proteins.log
genomes.ndb  genomes.njs  genomes.ntf  proteins.dmnd        viral_cluster_info.tsv`

Any insight into this? Thanks!

**Comment by snayfach** [comment]
Apologies, I forgot to uncomment a few lines of code, and should be fixed now - can you try again?

**Comment by haleyhallowell** [comment]
worked perfectly!! Thanks!
