### ISSUE TITLE
Phanta implementation and viromes other than the gut?

### ISSUE THREAD

**Issue by mhmism** [snayfach/UHGV#61]
Hello Stephen,

Thank you for this excellent resource. 

If I understand correctly, this database expands on the MGV database (also utilized in phanta). Therefore, this is supposedly a larger catalog of viruses that spans the human (gut?) virome. 

I have a couple of questions, and I hope that you can answer them.
1- Does this database only include "gut" viruses? or does it supposedly include viruses from other sampling compartments? so If I have a metagenomics dataset from the human oral cavity or the airways, can I still utilize this database? I am particularly thinking here about the IMG/VR 4 dataset which supposedly includes metagenomes from other locations than the gut.
2- Do the humgut_uhgv_hqplus_v1.tar.gz and humgut_uhgv_mqplus_v1.tar.gz databases correspond to the high-quality and medium-quality vOTUs, respectively? if so, does the humgut_uhgv_mqplus_v1.tar.gz include both the medium-quality and high-quality vOTUS or is it only restrictive to the medium-quality ones?

Thanks a lot in advance! I am looking forward to diving deep into this!

**Comment by snayfach** [comment]
> If I understand correctly, this database expands on the MGV database (also utilized in phanta). Therefore, this is supposedly a larger catalog of viruses that spans the human (gut?) virome.
Correct.

> 1- Does this database only include "gut" viruses?
Correct.

> 2- Do the humgut_uhgv_hqplus_v1.tar.gz and humgut_uhgv_mqplus_v1.tar.gz databases correspond to the high-quality and medium-quality vOTUs, respectively?
Correct. 

> if so, does the humgut_uhgv_mqplus_v1.tar.gz include both the medium-quality and high-quality vOTUS
Yes.
