### ISSUE TITLE
some questions baout result file 'taxon_info.tsv '

### ISSUE THREAD

**Issue by ChaoXianSen** [snayfach/UHGV#64]
Hello Stephen,

![e838718e81114ad6497f0addd788ccf](https://github.com/snayfach/UHGV/assets/26301954/9a7060b0-450c-49b9-beed-17c290b2c9df)

1. 'None','NA' indicates that there is no relevant classification information in the uhgv database?
2. what meanings of the values in the red box represent ?

Thanks for your reply!

**Comment by snayfach** [comment]
1. Correct, your sequence was not assigned at any rank. double check if this is a true human gut virus
2. The numbers in red indicates the annotation consistency for the viral taxon in the database to which your sequence in assigned.

Thanks for your questions -- we will update the docs accordingly

**Comment by ChaoXianSen** [comment]
> 1. Correct, your sequence was not assigned at any rank. double check if this is a true human gut virus
> 2. The numbers in red indicates the annotation consistency for the viral taxon in the database to which your sequence in assigned.
> 
> Thanks for your questions -- we will update the docs accordingly

Dear @snayfach 
I get it, thanks for your reply !
