### ISSUE TITLE
how many sequences in the UHGV databae ?

### ISSUE THREAD

**Issue by ChaoXianSen** [snayfach/UHGV#66]
Hi Stephen,
Thanks for your pipeline of human gut viruses classification.
I was trying to use the uhgv-tools to classifiy viral contigs, but I have some questions about UHGV database:

![077e8d825a3bea334c5073484c518a8](https://github.com/snayfach/UHGV/assets/26301954/ba97f921-c032-45f3-911c-8b8755162f3b)

![5dc61e16a813f0b959bde063298b79a](https://github.com/snayfach/UHGV/assets/26301954/39076d0e-09fa-4222-b5b0-9efc2b20d8da)

the number of sequence in 'genomes.fna' was the same as the species_level sequences. 'Where the number '208,643'  come from ?'

look forward your reply!

**Comment by snayfach** [comment]
Thanks for your question. 57514 is the number of high-quality, species level representatives, as indicated in the figure. Feel free to reopen if you have further questions.

**Comment by ChaoXianSen** [comment]
Hi,
I use checkV script aniclust.py to get specie_level votu: 
![image](https://github.com/snayfach/UHGV/assets/26301954/be2ab232-a096-48ed-8024-30c61de04489)

then, i use /MGV/aai_cluster/amino_acid_identity.py and filter_aai.py to get genus and family level votu:
genus_level cluster:
![image](https://github.com/snayfach/UHGV/assets/26301954/829db282-640f-4189-8972-4d343810c6aa)
 family_level cluster:
![image](https://github.com/snayfach/UHGV/assets/26301954/033b5746-98fc-4470-a4a8-70b9ab5804f4)

Q:  why genus and family level votu name has been changed ? What is the relationship between species level votu name and genus(family) level votu name?
