### ISSUE TITLE
uhgv-tools classify run error 

### ISSUE THREAD

**Issue by ChaoXianSen** [snayfach/UHGV#67]
There are some samples that do not work correctly ? Can you give me some advice

![image](https://github.com/snayfach/UHGV/assets/26301954/28f4a022-3705-4140-b7c9-2bedf9c44388)

**Comment by snayfach** [comment]
Please attach input file and I'll take a look.

**Comment by snayfach** [comment]
Did you try running the example dataset?

**Comment by snayfach** [comment]
This issue should be fixed if you try to install from scratch. Feel free to reopen if it persists
