### ISSUE TITLE
MCL-Cluster

### ISSUE THREAD

**Issue by Xuyang-Feng** [snayfach/UHGV#74]
Hi, when I used uhgv-tools, I had two questions.
1.what's threshold MCL uses when clustering, especially what edge weight is?
2.I notice that you used blast before cluster, I want to know do you perform additional processing on the data before conducting cluster analysis after obtaining the blast results?

Thank you.

**Comment by snayfach** [comment]
The current `uhgv-tools` script does not perform MCL, rather it performs classification using the best hit from ANI/AAI + taxon specific thresholds.

For creating the full database, those details will be available in the upcoming pre-print.
